### ISSUE TITLE
Create Repository Interfaces

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#19]
Create an `Repository` Interface using the _Repository Pattern_ and extend with an Interface for each of `Photopoint`, `Path`, and `Plant`
DoD:  Stated Interfaces completed

**Comment by silvioguiso** [comment]
The repo interface is created in issue 11. But right now it only contains 2 methods. So that might have to change.

**Comment by gomezfox** [comment]
Initial Interface completed by @silvioguiso in issue 11, which has been merged
