### ISSUE TITLE
Implement initial object Repositories

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#20]
Code initial implementations of the following repositories:  `PathRepository`, `PlantRepository`, `PhotopointRepository`. These will provide a layer of abstraction between static test data and logic/UI
DoD:  Repositories classes created and functional

**Comment by silvioguiso** [comment]
FYI, the photo point repo is created in issue 11. To be merged soon.

**Comment by gomezfox** [comment]
Merged into issue #30, pull request #43
