### ISSUE TITLE
Create sample photopoint data

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#21]
Create at least five near-real sample photopoints from data already gathered in person
DoD:  Array of `Photopoint` objects with complete data created and ready for Repository

**Comment by silvioguiso** [comment]
This is added in issue 11. I use them to plot photo-points on the map. But data-fields might have to be extended.

**Comment by gomezfox** [comment]
Merged in another issue, as have further updates since
