### ISSUE TITLE
Add QR Code property to PhotoPoint model

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#29]
The QR Code is a string associated with an individual PhotoPoint.  Currently resolves to a URL, but for this purpose will be used to return a `PhotoPoint` from its repository after scanning.

**Comment by silvioguiso** [comment]
We will need a property like this, but I am thinking that the QR-Code is kind of the ID of the photopoint. So, we could potentially use the QRCode for our ID.

**Comment by silvioguiso** [comment]
As discussed in class, we will add the QR Code property and have an integer-based auto generated ID column on all of our model entities.
