### ISSUE TITLE
Create Image model

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#41]
Items of the `Image` model type will contain the URI and metadata needed for other components to load an image from local app storage.  Initially this will include the URI, a foreign key for the `PointItem` that is imaged, an enumeration for the orientation (landscape, portrait, square), the height and width in pixels, and a source/license string.
DoD:  Model created to initial specs

**Comment by csuttner** [comment]
@gomezfox can I take ownership of this issue and delete my other irrelevant one?

**Comment by gomezfox** [comment]
@csuttner  The other isn't irrelevant, just not yet up to bat.  Modifying this one's scope now.
