### ISSUE TITLE
Research android constraints for children

### ISSUE THREAD

**Issue by silvioguiso** [MobileApps-Cascadia/photopoints-android#56]
We cannot use all the available libraries and services Google offers because there are age restrictions associated with them. Because of that, we need clear answers to the following questions.
* What age limitations, in terms of libraries and services, are there related to our app?
* What information are we not allowed to store if the user is not of age?
* What type authentications are we allowed to use?
* What are other restrictions we have to take into account?

DoD: The above answers are clearly documented with references to supporting materials. A Documentation folder should be added to the top level of the repository where we can store this information.

**Comment by Grant-Buchanan** [comment]
1. Data Collection:
 You must disclose the collection of any personal information from children in your app, including through APIs and SDKs called or used in your app.

2. APIs and SDKs:
You must ensure that your app properly implements any APIs and SDKs.
Apps that solely target children must not contain any APIs or SDKs that are not approved for use in child-directed services. This includes, Google Sign-In (or any other Google API Service that accesses data associated with a Google Account), Google Play Games Services, and any other API Service using OAuth technology for authentication and authorization.
Apps that target both children and older audiences should not implement APIs or SDKs that are not approved for use in child-directed services unless they are used behind a neutral age screen or implemented in a way that does not result in the collection of data from children (e.g., providing Google Sign-in as an optional feature). Note that all users must be able to access your app and a reasonable amount of its functionality.

3. Privacy policy:
You must provide a link to your app's privacy policy on your app's store listing page. This link must be maintained at all times while the app is available on the Store, and it must link to a privacy policy that, among other things, accurately describes your app's data collection and use.

4. Special restrictions:
If your app uses Augmented Reality, you must include a safety warning immediately upon launch of the AR section. The warning should contain the following:
An appropriate message about the importance of parental supervision.
A reminder to be aware of physical hazards in the real world (e.g., be aware of your surroundings).
Your app must not require the usage of a device that is advised not to be used by children. (e.g. Daydream, Oculus)

5. Legal Compliance: 
You must ensure that your app, including any APIs or SDKs that your app calls or uses, is compliant with the U.S. Children's Online Privacy and Protection Act (COPPA), E.U. General Data Protection Regulation (GDPR), and any other applicable laws or regulations. https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children's-privacy

**Comment by Grant-Buchanan** [comment]
Further guidelines: https://support.google.com/googleplay/android-developer/answer/9285070#neutral-agescreen

**Comment by Grant-Buchanan** [comment]
We can safely consider those under 18 as being children for the purposes of data collection.

**Comment by Grant-Buchanan** [comment]
https://support.google.com/families/answer/9131134?hl=en
