### ISSUE TITLE
Implement fragmentmanager transaction from recyclerview item to details fragment

### ISSUE THREAD

**Issue by Grant-Buchanan** [MobileApps-Cascadia/photopoints-android#74]
As it is now the details fragment doesn't really do much or go anywhere. The aim is to be able to send the user to the camera fragment once they navigate to the details fragment for a plant.
DoD: The details fragment uses the new fragment manager methods learned in class in order to send the user to the next fragment.
EDIT:
In order for the navigation to be implemented across the board, all fragments plus the main activity must use the fragment manager and accompanying methods.
DOD: All screens have an instance of the fragment manager 
EDIT 2:
It turns out that this whole navigate to a fragment from another fragment thing is a bit more difficult than I thought. I've lowered the bar for this issue again to just include navigating from a recycler view item to the details fragment.
DOD: tapping any item navigates from the recyclerview fragment to the details fragment.

**Comment by gomezfox** [comment]
Functionality is complete, but could use a new approach.  DoD requirements are met.  Changes will require a new issue.

**Comment by gomezfox** [comment]
an architectural change is needed, temporary solution implemented and closed with #101
