### ISSUE TITLE
Look through Silvio's code

### ISSUE THREAD

**Issue by Grant-Buchanan** [MobileApps-Cascadia/photopoints-android#76]
When we talked on Thursday we mentioned looking through Silvio's code and deciding if we have to change things in order for us to actually understand whats happening.
DoD: Not really sure what to put here, but this needs to be done in some form fairly soon.

**Comment by gomezfox** [comment]
I have already largely done this, and I believe we all should to the best of our abilities.  I am creating a new issue to begin the documentation, but we should confer as to what form that would take, at least initially.

**Comment by csuttner** [comment]
10-4 Stephen - thanks for letting us know. We can confer this afternoon

**Comment by csuttner** [comment]
I and @gomezfox have gone through the project line-by-line over the weekend, and I am now up to speed with how it works.
