### ISSUE TITLE
Begin code documentation in repository's Wiki

### ISSUE THREAD

**Issue by gomezfox** [MobileApps-Cascadia/photopoints-android#78]
DoD:  Wiki associated with the app repository is enabled, start page and a few initial stubs are created

**Comment by gomezfox** [comment]
Wiki has been started, contains an index page for data models, a stub for material design, and a custom sidebar

**Comment by csuttner** [comment]
Nice start to the documentation Stephen

**Comment by gomezfox** [comment]
The documentation has been started.  The rest of existing design needs documentation, as does each new element as it is added.
