### ISSUE TITLE
Show plant images in card view.

### ISSUE THREAD

**Issue by csuttner** [MobileApps-Cascadia/photopoints-android#89]
DOD: plant images in resources/raw are linked to display in card view.

**Comment by gomezfox** [comment]
Likely depends on #41.

**Comment by csuttner** [comment]
Thanks @gomezfox lets look at that today

**Comment by csuttner** [comment]
Moved this off the current sprint - focusing on issue #41 first per @gomezfox's direction.

**Comment by gomezfox** [comment]
Closing issue as it was included with pull request #115
